POST http://localhost:5000/api/signup
Content-Type: application/json

{
    "firstName": "nova",
    "lastName": "khan", 
    "email": "nova@gmail.com", 
    "password": "12345nova",
    "contactNumber": "1251251"
}