POST http://localhost:5000/api/signup
Content-Type: application/json

{
    "firstName": "sakib",
    "lastName": "alamin", 
    "email": "sakib@gmail.com", 
    "password": "sakib12345",
    "contactNumber": "sakibpassword"
}

### 

POST http://localhost:5000/api/signin
Content-Type: application/json

{
    "email": "sakib@gmail.com",
    "password": "sakib12345"
}

###

POST http://localhost:5000/api/admin/signup
Content-Type: application/json

{
    "firstName": "nova",
    "lastName": "khan", 
    "email": "novakhan@gmail.com", 
    "password": "novapassword",
    "contactNumber": "1234566"
}

###

POST http://localhost:5000/api/admin/signin
Content-Type: application/json

{
    "email": "novakhan@gmail.com", 
    "password": "novapassword"
}

###
POST http://localhost:5000/api/signin
Content-Type: application/json

{
    "email": "skdfjsd@gmail.com",
    "password": "123456"
}

###
POST http://localhost:5000/api/category/create
Content-Type: application/json 

{
    "name": "TestCategory"
}

###
POST http://localhost:5000/api/category/create
Content-Type: application/json

{
    "name": "Vegetables"
}

###
POST http://localhost:5000/api/category/create
Content-Type: application/json

{
    "name": "Dairy"
}

###
POST http://localhost:5000/api/category/create
Content-Type: application/json

{
    "name": "Homemade"
}

###
GET http://localhost:5000/api/category/getcategory



